#requires -Version 5
<#
  gx10-swap installer - makes `gswap` work from any shell.

  What it does:
    1. Writes a `gswap.cmd` shim into %USERPROFILE%\.local\bin that calls this
       repo's gx10_swap.py (so edits to the script take effect with no reinstall).
       This serves cmd.exe and Git Bash.
    2. Registers a native PowerShell `gswap` function in your $PROFILE, so PowerShell
       runs the script directly (no cmd.exe dependency).
    3. Ensures %USERPROFILE%\.local\bin is on your *persistent* user PATH.

  Run once:  powershell -ExecutionPolicy Bypass -File .\install.ps1
  Uninstall: .\install.ps1 -Uninstall
#>
param([switch]$Uninstall)

$ErrorActionPreference = 'Stop'

$repo   = $PSScriptRoot                                  # this repo, wherever it lives
$script = Join-Path $repo 'gx10_swap.py'
$binDir = Join-Path $env:USERPROFILE '.local\bin'        # same dir cswap uses; on PATH
$shim   = Join-Path $binDir 'gswap.cmd'

$MarkBegin = '# >>> gswap (gx10-swap) >>>'
$MarkEnd   = '# <<< gswap (gx10-swap) <<<'

function Remove-ProfileBlock {
    if (-not (Test-Path $PROFILE)) { return $false }
    $content = Get-Content $PROFILE -Raw
    $pattern = "(?ms)\r?\n?" + [regex]::Escape($MarkBegin) + ".*?" + [regex]::Escape($MarkEnd) + "\r?\n?"
    if ($content -notmatch $pattern) { return $false }
    [IO.File]::WriteAllText($PROFILE, ([regex]::Replace($content, $pattern, "`r`n")).TrimEnd() + "`r`n")
    return $true
}

if ($Uninstall) {
    if (Test-Path $shim) { Remove-Item $shim; Write-Host "Removed $shim" -ForegroundColor Yellow }
    else { Write-Host "Nothing to remove ($shim not found)." }
    if (Remove-ProfileBlock) { Write-Host "Removed gswap function from $PROFILE" -ForegroundColor Yellow }
    Write-Host "Left $binDir on PATH (other tools like cswap may use it)."
    return
}

if (-not (Test-Path $script)) { throw "gx10_swap.py not found next to installer at $script" }
if (-not (Get-Command python -ErrorAction SilentlyContinue)) {
    Write-Warning "python not found on PATH - install Python 3.11+ or gswap won't run."
}

# 1. shim - written CRLF so batch parsing doesn't choke on comment lines.
New-Item -ItemType Directory -Force -Path $binDir | Out-Null
$lines = @(
    '@echo off',
    'REM gswap shim (generated by install.ps1) - calls the repo script directly.',
    "python `"$script`" %*"
)
[IO.File]::WriteAllText($shim, ($lines -join "`r`n") + "`r`n")
Write-Host "Installed shim: $shim  ->  $script" -ForegroundColor Green

# 2. native PowerShell function in $PROFILE (no cmd.exe dependency).
Remove-ProfileBlock | Out-Null   # drop any prior block so we don't stack duplicates
New-Item -ItemType Directory -Force -Path (Split-Path $PROFILE) | Out-Null
$block = @"
$MarkBegin
function gswap { python "$script" @args }
$MarkEnd
"@
Add-Content -Path $PROFILE -Value $block -Encoding UTF8
# usable in THIS PowerShell session too.
function gswap { python "$script" @args }
Write-Host "Registered PowerShell function in $PROFILE" -ForegroundColor Green

# 3. ensure ~/.local/bin is on the persistent user PATH.
$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
$onPath = ($userPath -split ';' | Where-Object { $_.TrimEnd('\') -ieq $binDir.TrimEnd('\') })
if (-not $onPath) {
    $newPath = if ([string]::IsNullOrEmpty($userPath)) { $binDir } else { "$($userPath.TrimEnd(';'));$binDir" }
    [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
    Write-Host "Added $binDir to your user PATH (open a NEW terminal to pick it up)." -ForegroundColor Green
} else {
    Write-Host "$binDir already on PATH." -ForegroundColor DarkGray
}

# 4. make the PATH shim usable in THIS session immediately.
if (($env:Path -split ';' | Where-Object { $_.TrimEnd('\') -ieq $binDir.TrimEnd('\') }).Count -eq 0) {
    $env:Path = "$env:Path;$binDir"
}
Write-Host ""
Write-Host "Done. Try:  gswap list   (open a new terminal if PATH/profile was just changed)" -ForegroundColor Cyan
